[workspace]
resolver = "2"
members = [
    "crates/jumpy",
    "crates/bevy-has-load-progress",
    "crates/bevy-has-load-progress/macros",
]

[profile.dev.package."*"]
opt-level = 1 # Set this to 3 if the game becomes slow to respond during gameplay
debug = false

[profile.release]
lto = true
codegen-units = 1 # Improves physics performance for release builds