name: CI

on:
  push:
    branches:
      - master
      - staging
      - trying
  pull_request:

jobs:
  check_formatting:
    runs-on: ubuntu-latest
    name: Check Rust formatting
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy_correctness_checks:
    runs-on: ubuntu-latest
    name: Clippy correctness checks
    strategy:
      fail-fast: false
      matrix:
        config:
          - { target: 'x86_64-unknown-linux-gnu', target_dir: 'target' }
          - { target: 'wasm32-unknown-unknown', target_dir: 'web-target' }
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y -q \
              libasound2-dev \
              libudev-dev
      - uses: actions/checkout@v3
      - name: Install WASM Target
        if: matrix.config.target == 'wasm32-unknown-unknown'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.config.target }}
          components: clippy
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            web-target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1
        env:
          CARGO_TARGET_DIR: ${{ matrix.config.target_dir }}
        with:
          command: clippy
          args: --target ${{ matrix.config.target }} -- -W clippy::correctness -D warnings
